- hosts: web 
  sudo: True
  user: vagrant
  vars_files:
    - vars/wordpress.yml
    - vars/mysql.yml
  roles:
    - common
    - php
    - nginx
    - wordpress

- hosts: db 
  sudo: True
  user: vagrant
  vars_files:
    - vars/mysql.yml
  roles:
    - common
    - mysql
